function p = initparam()

p = struct('nFineGroups', [], ...
            'nFewGroups', [], ...
          'fineGroupDef', [], ...
           'fewGroupDef', [], ...
            'nTimeSteps', 1, ...
             'resolveXS', 1, ... % Does self-shielding.
           'makeLibrary', 1, ...
   'makeLibraryTempFlag', struct(), ... % can pass a FarmXS input structure.
               'verbose', 1, ...
          'XSLibraryMAT', '', ...
'waterTransportFromParts', 0, ...
        'immutableMyMTs', 2, ... % Decides when derived xs's are made.
     'makeRealNuFission', 1, ... % Previously just fission was used in CPM.
          'S0iterthresh', 0.00001, ...
                'doPlot', 0 ... % Controls plotting in Postprocessor.m
    );

end
