function transportanalysis(g, L, Results)
Ri = Results.Region(1);
r = g.regionDef(1);
mt = [7 8 102 2];
for iCell = 1:r.nCells
    for iZAID = 1:length(r.cellDef(iCell).initZAIDs)
        ZAID = r.cellDef(iCell).initZAIDs(iZAID);
        figure;
        absorb = Ri.Cell(iCell).fine(L.MT(18)).z(iZAID).s + ...
                Ri.Cell(iCell).fine(L.MT(102)).z(iZAID).s;
        totmintrans = Ri.Cell(iCell).fine(L.MT(7)).z(iZAID).s - ...
            Ri.Cell(iCell).fine(L.MT(8)).z(iZAID).s;
            if any(totmintrans < 0)
                fprintf('zeros at %s %i', r.cellDef(iCell).name, ZAID);
            end
        loglog(L.groupDef(1:end-1), [Ri.Cell(iCell).fine(L.MT(7)).z(iZAID).s ...
                          Ri.Cell(iCell).fine(L.MT(8)).z(iZAID).s ...
            absorb ...
                      sum(Ri.Cell(iCell).fine(L.MT(2)).z(iZAID).s)' ...
            totmintrans]);
%Ri.Cell(iCell).fine(L.MT(8)).value - absorb]);
        legend('total', 'transport', 'absorb', 'scatter','total-transport');
        title(sprintf('cell %s zaid %i', r.cellDef(iCell).name, ZAID));
                        
    end
    figure;
        absorb = Ri.Cell(iCell).fine(L.MT(18)).value + ...
                Ri.Cell(iCell).fine(L.MT(102)).value;
        totmintrans = Ri.Cell(iCell).fine(L.MT(7)).value - ...
            Ri.Cell(iCell).fine(L.MT(8)).value;
        loglog(L.groupDef(1:end-1), [Ri.Cell(iCell).fine(L.MT(7)).value ...
                          Ri.Cell(iCell).fine(L.MT(8)).value ...
            absorb ...
                      sum(Ri.Cell(iCell).fine(L.MT(2)).value)' ...
            totmintrans]);
%Ri.Cell(iCell).fine(L.MT(8)).value - absorb]);
        legend('total', 'transport', 'absorb', 'scatter','total-transport');
        title(sprintf('cell %s', r.cellDef(iCell).name));
end

figure; % mubar
semilogx(L.groupDef(1:end-1), [ ...
    Ri.Cell(1).fine(L.MT(251)).z(1).s, ...
    Ri.Cell(1).fine(L.MT(251)).z(2).s, ...
    Ri.Cell(2).fine(L.MT(251)).z(1).s, ...
    Ri.Cell(2).fine(L.MT(251)).z(2).s, ...
    Ri.Cell(2).fine(L.MT(251)).z(3).s, ...
    ]);
title('mubar in all cells and zaids');
legend('water H', 'water O', 'uo2 U235', 'uo2 U238', 'uo2 O');
