% to run this script you need to run sandboxall running sandboxfastnative6
% this shows a discrepancy between my inelastic vector from NJOY and the
% inelastic vector that i can make from geoff's summation.

load('XSLibrary_inelastic_byGeoff_120103');

ZAIDs = [92235 92238 11023 8016];
for i = 1:4
    xs1 = L.z(L.ZAID(ZAIDs(i))).m(L.MT(4)).xs(:,1,1);
    xs2 = sum(B{i}.m(2).kern(:,:,1,1))';
    printplotxsn('', ['inelasticdiscrepancy' num2str(ZAIDs(i)) 'mt4'],...
        0,0,0,[],'', {...
        'FarmXS','Geoff''s sum'...
        },[], ...
        L.groupDef, {xs1 xs2});
    xs3 = sum(L.z(L.ZAID(ZAIDs(i))).m(L.MT(2)).xs(:,:,1,1))';
    xs4 = sum(B{i}.m(3).kern(:,:,1,1))';
    printplotxsn('', ['inelasticdiscrepancy' num2str(ZAIDs(i)) 'mt2'],...
        0,0,0,[],'', {...
        'FarmXS','Geoff''s sum'...
        },[], ...
        L.groupDef, {xs3 xs4});
end

   fid = fopen('inelasticdiscrepancyreport.tex','w');
   fprintf(fid,'\\documentclass[letterpaper,12pt]{article}\n');
   fprintf(fid,'\\usepackage{graphicx}\n')'
   fprintf(fid,'\\usepackage[left=.5in,right=.5in,top=1in,bottom=1in]{geometry}\n');
   fprintf(fid,'\\usepackage{caption}\n');
   fprintf(fid,'\\newcommand{\\fitzefigtwo}[2]{\\begin{center}\\includegraphics{#1}\\captionof{figure}{#2}\\label{fig:#2}\\end{center}}\n');
   fprintf(fid,'\\begin{document}\n');
   fprintf(fid,'\\title{Inelastic cross section discrepancy}\n');
   fprintf(fid,'\\date{\\today}\n');
   fprintf(fid,'\\maketitle\n');


for i = 1:4
   fprintf(fid,['\\fitzefigtwo{inelasticdiscrepancy' num2str(ZAIDs(i)) ...
       'mt4}{Energy dependent inelastic vector for ZAID ' num2str(ZAIDs(i)) ...
       ', generated by FarmXS (and combined with Geoff''s inelastic kernel)'...
       ' and from Geoff''s sum of MTs 51 through 91.}\n']);
   fprintf(fid,['\\fitzefigtwo{inelasticdiscrepancy' num2str(ZAIDs(i)) ...
   'mt2}{Energy dependent elastic vector for ZAID ' num2str(ZAIDs(i)) ...
   ', generated by FarmXS and from Geoff''s sum of MTs 51 through 91.}\n']);

end

   fprintf(fid,'\\end{document}\n');
   fclose(fid);

   system('rubber --pdf inelasticdiscrepancyreport.tex');
