
% to run this script you need to run sandboxall running sandboxfastnative6
% this shows a discrepancy between my inelastic vector from NJOY and the
% inelastic vector that i can make from geoff's summation.


ZAIDs = [92235 92238 11023 8016];
for i = 1:length(ZAIDs)
    xs1 = L.z(L.ZAID(ZAIDs(i))).m(L.MT(4)).xs(:,1,1);
    xs2 = sum(L.z(L.ZAID(ZAIDs(i))).m(L.MT(6)).xs(:,:,1,1))';
    printplotxsn('', ['inelasticMYdiscrepancy' num2str(ZAIDs(i)) 'mt4'],...
        0,0,0,[],'', {...
        'FarmXS inelastic vector','inelastics kernel sum'...
        },[], ...
        L.groupDef, {xs1 xs2});
end

   fid = fopen('inelasticMYdiscrepancyreport.tex','w');
   fprintf(fid,'\\documentclass[letterpaper,12pt]{article}\n');
   fprintf(fid,'\\usepackage{graphicx}\n')'
   fprintf(fid,'\\usepackage[left=.5in,right=.5in,top=1in,bottom=1in]{geometry}\n');
   fprintf(fid,'\\usepackage{caption}\n');
   fprintf(fid,'\\newcommand{\\fitzefigtwo}[2]{\\begin{center}\\includegraphics{#1}\\captionof{figure}{#2}\\label{fig:#2}\\end{center}}\n');
   fprintf(fid,'\\begin{document}\n');
   fprintf(fid,'\\title{Inelastic cross section discrepancy}\n');
   fprintf(fid,'\\date{\\today}\n');
   fprintf(fid,'\\maketitle\n');


for i = 1:length(ZAIDs)
   fprintf(fid,['\\fitzefigtwo{inelasticMYdiscrepancy' num2str(ZAIDs(i)) ...
       'mt4}{Energy dependent inelastic vector for ZAID ' num2str(ZAIDs(i)) ...
       ', generated by FarmXS and inelastic kernel (MTs 51 through less '...
       'than 91) generated by FarmXS.}\n']);

end

   fprintf(fid,'\\end{document}\n');
   fclose(fid);

   system('rubber --pdf inelasticMYdiscrepancyreport.tex');
