function param = DeclareParam()

%{
%% PL PL PL PL PL PL PL PL
pL = struct('metamat','FarmXSMeta',...
            'address','/home/fitze/LANL/XSFarmSerpentFast',...
            'verbose',1,...
            'explore',0,...
               'mine',0,...
              'plant',0,...
          'fertilize',0,...
            'harvest',0,...
                 'e',struct('searchWeb',1),...
                 'm',struct('downloadTape20s',1),...
                 'p',struct('MFMTs',[3 1;
                                     3 4;
                                     6 2;
                                     3 18;
                                     3 102;
                                     3 251;
                                     3 452],...
                     'farmInelastic',1,...
                                'Ts',[296 450 600 1000],...
                              'S0s',10.^([10 5 3 2 1 0 -1]),...
                           'IGNstr','1',...
                         'groupDef',10.^(-4:.1:7),...
                           'IWTstr','3'),...
                 'f',struct('overwriteOutput',1,...
                                 'logResults',0),...
                 'h',struct('makeLibrary',1,...
                             'makeArrays',0),...
             'ZAIDs',[1001 8016 11023 92235 92238]);


%% DEFINE PARAMETER STRUCTURE P P P P P P P
fineGroupDef = 10.^(-4:.1:7);
fewGroupDef = [1e-4 1 100e3 1e7];
p = struct('nFineGroups',length(fineGroupDef)-1,... % leave blank.
    'nFewGroups',length(fewGroupDef)-1,...
    'fineGroupDef',fineGroupDef,...
    'fewGroupDef',fewGroupDef,...
    'powerDensity',50,... % MW/m^3
    'nTimeSteps',1,...
    'makeLibrary',0,...
    'makeLibraryTempFlag',pL,... %3,...
    'XSLibraryMAT','XSLibrarySerpentFast.mat',...
    'verbose',1,...
    'resolveXS',1,...
    'immutableMyMTs',1,...
    'makeRealNuFission',1,...
    'S0iterthresh',.00001,...
    'doPlot',0); % this largely affects the validation effort.



param = struct(
end

%}
